### PR TITLE
Small cleanup.

### PR DESCRIPTION
**Pull request by TehSteel**
Small cleanup.

Changed GetDistanceBetweenCoords to lua math check.
Changed table.insert and table.remove to `tableName[#tableName+1] = whatever` and `tableName[id] = nil`.
Made models after spawning to unload from memory using `SetModelAsNoLongerNeeded`.

### CODE REVIEW

**Comment by Andyauk** [comment]
not fully tested it. but you do have an error `@ps-drugprocessing/client/sulfuricacid.lua:87
`From
`if #(coords - GetEntityCoords(SulfuricAcidBarrels[i])) < 2`
to
		`if #(coords - GetEntityCoords(SulfuricAcidBarrels[i])) < 2 then`

**Comment by TehSteel** [comment]
> not fully tested it. but you do have an error `@ps-drugprocessing/client/sulfuricacid.lua:87 ` change from `if #(coords - GetEntityCoords(SulfuricAcidBarrels[i])) < 2` to `if #(coords - GetEntityCoords(SulfuricAcidBarrels[i])) < 2 then`

Oopsy daisy, Fixed it 🥲

**Comment by MonkeyWhisper** [comment]
Hi, thanks for the cleanup... much needed as this resource is pretty outdated but still works.

Has this been tested in a live environment?

**Comment by MonkeyWhisper** [comment]
> Small cleanup.
> 
> Changed GetDistanceBetweenCoords to lua math check. Changed table.insert and table.remove to `tableName[#tableName+1] = whatever` and `tableName[id] = nil`. Made models after spawning to unload from memory using `SetModelAsNoLongerNeeded`.

https://github.com/Project-Sloth/ps-drugprocessing/pull/106#issue-1532288461

**Comment by MonkeyWhisper** [comment]
> Small cleanup.
> 
> Changed GetDistanceBetweenCoords to lua math check. Changed table.insert and table.remove to `tableName[#tableName+1] = whatever` and `tableName[id] = nil`. Made models after spawning to unload from memory using `SetModelAsNoLongerNeeded`.

Thanks for the cleanup, much needed, this resource is quite old already.

Are these changes live in a server and working as intended?

**Comment by TehSteel** [comment]
> > Small cleanup.
> > Changed GetDistanceBetweenCoords to lua math check. Changed table.insert and table.remove to `tableName[#tableName+1] = whatever` and `tableName[id] = nil`. Made models after spawning to unload from memory using `SetModelAsNoLongerNeeded`.
> 
> Thanks for the cleanup, much needed, this resource is quite old already.
> 
> Are these changes live in a server and working as intended?

No, Will put it tomorrow in a live server.

**Comment by Andyauk** [comment]
> > Small cleanup.
> > Changed GetDistanceBetweenCoords to lua math check. Changed table.insert and table.remove to `tableName[#tableName+1] = whatever` and `tableName[id] = nil`. Made models after spawning to unload from memory using `SetModelAsNoLongerNeeded`.
> 
> Thanks for the cleanup, much needed, this resource is quite old already.
> 
> Are these changes live in a server and working as intended?

I've had it in for just under 2 weeks no real issue. but I don't do everything. ill ask people of my city if they had any issues.

**Comment by TehSteel** [comment]
> > Small cleanup.
> > Changed GetDistanceBetweenCoords to lua math check. Changed table.insert and table.remove to `tableName[#tableName+1] = whatever` and `tableName[id] = nil`. Made models after spawning to unload from memory using `SetModelAsNoLongerNeeded`.
> 
> Thanks for the cleanup, much needed, this resource is quite old already.
> 
> Are these changes live in a server and working as intended?

Worked fine for me.

**Comment by Andyauk** [comment]
> > > Small cleanup.
> > > Changed GetDistanceBetweenCoords to lua math check. Changed table.insert and table.remove to `tableName[#tableName+1] = whatever` and `tableName[id] = nil`. Made models after spawning to unload from memory using `SetModelAsNoLongerNeeded`.
> > 
> > 
> > Thanks for the cleanup, much needed, this resource is quite old already.
> > Are these changes live in a server and working as intended?
> 
> Worked fine for me.

yes worked fine. tested all.

**Review by MonkeyWhisper — APPROVED** [review]

**Pull request merged**
