### PR TITLE
bug fixes (Coke, Meth)

### PR DESCRIPTION
**Pull request by Alivemonstor**

### CODE REVIEW

**Review by DarrianJCairns — CHANGES_REQUESTED** [review]
Missing Comma line 42

**Comment by Alivemonstor** [comment]
> Missing Comma line 42 - Client/Coke

fixed already

**Review by DarrianJCairns — CHANGES_REQUESTED** [review]
Might need to tweak the Enter for Coke, if you stand of "Draco" from the door it doesnt work.. Stand closer to the door and Third eye him does work

**Comment by Alivemonstor** [comment]
> Might need to tweak the Enter for Coke, if you stand of "Draco" from the door it doesnt work.. Stand closer to the door and Third eye him does work

that's what I did

**Comment by DarrianJCairns** [comment]
> > Might need to tweak the Enter for Coke, if you stand of "Draco" from the door it doesnt work.. Stand closer to the door and Third eye him does work
> 
> that's what I did

Ohh doesnt seem to work, let me double check

**Comment by Alivemonstor** [comment]
> > > Might need to tweak the Enter for Coke, if you stand of "Draco" from the door it doesnt work.. Stand closer to the door and Third eye him does work
> > 
> > 
> > that's what I did
> 
> Ohh doesnt seem to work, let me double check

I can tweak again if necessary

**Comment by Alivemonstor** [comment]
> > > Might need to tweak the Enter for Coke, if you stand of "Draco" from the door it doesnt work.. Stand closer to the door and Third eye him does work
> > 
> > 
> > that's what I did
> 
> Ohh doesnt seem to work, let me double check

works fine for me

**Comment by DarrianJCairns** [comment]
> > > > Might need to tweak the Enter for Coke, if you stand of "Draco" from the door it doesnt work.. Stand closer to the door and Third eye him does work
> > > 
> > > 
> > > that's what I did
> > 
> > 
> > Ohh doesnt seem to work, let me double check
> 
> works fine for me

https://medal.tv/games/gta-v/clips/jaU9IT2x6g5nt/d133745fxeHQ?invite=cr-MSw1UzgsMzE3NTM2MTEs

**Comment by Alivemonstor** [comment]
> > > > > Might need to tweak the Enter for Coke, if you stand of "Draco" from the door it doesnt work.. Stand closer to the door and Third eye him does work
> > > > 
> > > > 
> > > > that's what I did
> > > 
> > > 
> > > Ohh doesnt seem to work, let me double check
> > 
> > 
> > works fine for me
> 
> https://medal.tv/games/gta-v/clips/jaU9IT2x6g5nt/d133745fxeHQ?invite=cr-MSw1UzgsMzE3NTM2MTEs

restart server

**Comment by DarrianJCairns** [comment]
> > > > > > Might need to tweak the Enter for Coke, if you stand of "Draco" from the door it doesnt work.. Stand closer to the door and Third eye him does work
> > > > > 
> > > > > 
> > > > > that's what I did
> > > > 
> > > > 
> > > > Ohh doesnt seem to work, let me double check
> > > 
> > > 
> > > works fine for me
> > 
> > 
> > https://medal.tv/games/gta-v/clips/jaU9IT2x6g5nt/d133745fxeHQ?invite=cr-MSw1UzgsMzE3NTM2MTEs
> 
> restart server

Might need to change the Cutting Coke required items to include the "finescale" item too

**Comment by DarrianJCairns** [comment]
Defo seems the "exports["qb-target"]:AddBoxZone("cokebricked", vector3(1098.77, -3194.19, -38.99), 2.6, 1.0, {"

For processing the Bricks isnt correct

**Comment by Alivemonstor** [comment]
> Defo seems the "exports["qb-target"]:AddBoxZone("cokebricked", vector3(1098.77, -3194.19, -38.99), 2.6, 1.0, {"
> 
> For processing the Bricks isnt correct

fixed

**Comment by DarrianJCairns** [comment]
> > Defo seems the "exports["qb-target"]:AddBoxZone("cokebricked", vector3(1098.77, -3194.19, -38.99), 2.6, 1.0, {"
> > For processing the Bricks isnt correct
> 
> fixed

Works great, is there somewhere to process the "bricks" into bags?

**Pull request merged**
